image: node:14

before_script:
  - apt-get update -qq && apt-get install -y -qq sshpass rsync

stages:
  - build
  - deploy_staging
  - deploy_production

cache:
  paths:
    - node_modules

build:
  except:
    - tags
  stage: build
  artifacts:
    paths:
      - __sapper__/
      - static/
  script:
    - npm ci
    - npm run build

deploy_staging:
  stage: deploy_staging
  needs: [build]
  script:
    - source .ci/deploy-staging

deploy_production:
  only:
    - master
  except:
    - tags
  stage: deploy_production
  needs: [build, deploy_staging]
  script:
    - source .ci/deploy-production
