#!/usr/bin/env bash

export SSHPASS=$CI_USER_PASS
sshpass -e ssh -o StrictHostKeyChecking=no -p 922 $CI_USER@$CI_HOST 'cd /var/www/david-klimes-web/current;PM2_HOME=/var/www/.pm2 pm2 stop process.json;cd ..;rm -rf current'
sshpass -e rsync -rzq -e 'ssh -o StrictHostKeyChecking=no -p 922' . $CI_USER@$CI_HOST:/var/www/david-klimes-web/current
sshpass -e ssh $CI_USER@$CI_HOST 'ln -s /var/www/david-klimes-web/shared/.env /var/www/david-klimes-web/current/.env;cd /var/www/david-klimes-web/current;PM2_HOME=/var/www/.pm2 pm2 start process.json --env production'
